sylius_twig_hooks:
    hooks:
        # Add synchronize button to exchange rate index page header actions
        'sylius_admin.exchange_rate.index.content.header.title_block.actions':
            synchronize_button:
                template: '@AdeliomSyliusExchangeRatePlugin/admin/exchange_rate/_synchronize_button.html.twig'
                priority: 10
