#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    SyliusExchangeRagePlugin-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^syliusexchangerageplugin\.ddev\.site$`)
      
      service: "SyliusExchangeRagePlugin-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "SyliusExchangeRagePlugin-redirectHttps"
    SyliusExchangeRagePlugin-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^syliusexchangerageplugin\.ddev\.site$`)
      
      service: "SyliusExchangeRagePlugin-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "SyliusExchangeRagePlugin-redirectHttps"
    SyliusExchangeRagePlugin-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^syliusexchangerageplugin\.ddev\.site$`)
      
      service: "SyliusExchangeRagePlugin-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "SyliusExchangeRagePlugin-redirectHttps"
    
    
    
    SyliusExchangeRagePlugin-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^syliusexchangerageplugin\.ddev\.site$`)
      
      service: "SyliusExchangeRagePlugin-web-80"
      ruleSyntax: v3
      
      tls: true
      
    SyliusExchangeRagePlugin-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^syliusexchangerageplugin\.ddev\.site$`)
      
      service: "SyliusExchangeRagePlugin-web-8025"
      ruleSyntax: v3
      
      tls: true
      
    
    SyliusExchangeRagePlugin-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^syliusexchangerageplugin\.ddev\.site$`)
      
      service: "SyliusExchangeRagePlugin-xhgui-80"
      ruleSyntax: v3
      
      tls: true
      
    

  middlewares:
    SyliusExchangeRagePlugin-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    SyliusExchangeRagePlugin-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-SyliusExchangeRagePlugin-web:80
        
    SyliusExchangeRagePlugin-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-SyliusExchangeRagePlugin-web:8025
        
    
    
    SyliusExchangeRagePlugin-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-SyliusExchangeRagePlugin-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/SyliusExchangeRagePlugin.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/SyliusExchangeRagePlugin.key